title:             Welcome
email:             me15btech11009@iith.ac.in
description:       Personal website of Deepak Nathani
author:            Deepak Nathani
baseurl:           ""
url:               ""

# Social Profiles
twitter_username:  deepaknathani11
github_username:   deepakn97
linkedin_username: deepak-nathani
googlescholar_link: https://scholar.google.com/citations?user=ItTsP6IAAAAJ&hl=en

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
